version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=test
  ftp:
    image: bogem/ftp
    ports:
      - '20:20'
      - '21:21'
      - '47400-47470:47400-47470'
    environment:
      - FTP_USER=test
      - FTP_PASS=1234
      - PASV_ADDRESS='127.0.0.1'